#cloud-config
hostname: test-img
manage_etc_hosts: true
fqdn: test-img
user: test
password: $5$cX3RQFNN$H5qNtruoNzcY9eFGVjVEpKAG4poGZb3mXeBJ82Q8mP4
ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPpqF0ArLl773210n2vT2G5MPBrdEzYbPdjcPokeEGJW willjasen
chpasswd:
  expire: False
users:
  - default
package_upgrade: true
packages:
  - curl
  - git
  - wget
  - net-tools
  - screen
  - jq
  - locate
  - nano
  - ssh
  - openssl
  - qemu-guest-agent
  - cryptsetup
  - gparted
  - htop
  - nmon
  - iotop
  - iputils-ping
  - traceroute
  - dnsutils
  - build-essentials
runcmd:
  - [ systemctl, daemon-reload ]
  - [ systemctl, enable, qemu-guest-agent.service ]
  - [ systemctl, start, qemu-guest-agent.service ]
  - [ 'sh', '-c', 'curl -fsSL https://tailscale.com/install.sh | sh' ]
  - [ 'wget', 'https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb']
  - [ 'dpkg', '-i', 'zabbix-release_6.4-1+ubuntu22.04_all.deb' ]
  - [ apt, update ]
  - [ 'apt', 'install', 'zabbix-agent2', '-y']
  - [ systemctl, enable, zabbix-agent2.service ]
  - [ systemctl, start, zabbix-agent2.service ]
